
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 13;
  public static final int ELSE = 7;
  public static final int PLUS = 11;
  public static final int RPAREN = 16;
  public static final int THEN = 6;
  public static final int SEMI = 4;
  public static final int END = 8;
  public static final int AS = 3;
  public static final int IF = 5;
  public static final int LPAREN = 15;
  public static final int NUMBER = 17;
  public static final int EOF = 0;
  public static final int DIVIDE = 14;
  public static final int MINUS = 12;
  public static final int error = 1;
  public static final int ABOUT = 10;
  public static final int BOOL = 19;
  public static final int STORE = 2;
  public static final int THINK = 9;
  public static final int VAR = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STORE",
  "AS",
  "SEMI",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "THINK",
  "ABOUT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "VAR",
  "BOOL"
  };
}

